/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCall */

#ifndef _Included_JavaCall
#define _Included_JavaCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaCall
 * Method:    mpc
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_JavaCall_mpc
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     JavaCall
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaCall_load
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
