/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCall */

#ifndef _Included_JavaCall
#define _Included_JavaCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaCall
 * Method:    sumAndAverage
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_JavaCall_sumAndAverage
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
